name: "techunico-js-event-logger"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: event-logger-release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: publish
#       - run: npm ci
#       - run: npm publish
        run: npm publish --access public
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.PRETTIER_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
